services:
  jafkafe:
    build: .
    image: freeds/jafkafe:latest
    container_name: jafkafe
    environment:
      FDS_CONFIG_URL: ${FDS_CONFIG_URL}
      FDS_KAFKA_BOOTSTRAP_SERVERS : ${FDS_KAFKA_BOOTSTRAP_SERVERS}
      FDS_ROOT_PATH: "/opt"

    volumes:
      - "${FDS_ROOT_PATH}/data/jafkafe:/opt/data/jafkafe"
    networks:
      - freeds-network

networks:
  freeds-network:
    name: freeds-network
    external: true
