[project]
name = "freeds-lab-jaffle-kafe"
version = "0.1.0"
description = ""
authors = [
    {name = "freeds@jensbox.se"}
]
license = {text = "GNU v 3"}
readme = "README.md"
requires-python = ">=3.11, <4.0"

[tool.poetry]
packages = [
    { include = "jafkafe", from = "src" }
]

[tool.poetry.dependencies]
jafgen = { path = "../../jaffle-shop-generator", develop = true }
loguru = "^0.7.3"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
